# Generated by Django 3.2.17 on 2023-02-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('amt', models.FloatField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
