# Generated by Django 3.2.17 on 2023-02-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_filter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
