# Generated by Django 3.2.17 on 2023-02-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_filter', '0002_remove_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Pending', max_length=8),
        ),
    ]
